# Generated by Django 4.2.11 on 2024-04-17 22:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=250, null=True)),
                ('amount', models.PositiveBigIntegerField(blank=True, default=0, null=True)),
                ('method', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=100, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_announced', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
    ]
